# Generated by Django 2.0.2 on 2018-02-08 05:39

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='myuuid',
            field=models.PositiveIntegerField(default=polls.models.get_my_uuid),
        ),
    ]
